/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/
    #define EE_MAX_EVENT 3
    #if 3 > 0
    #define ev_button 0x1U
    #endif
    #if 3 > 1
    #define ev_timeout 0x2U
    #endif
    #if 3 > 2
    #define ev_randTime 0x4U
    #endif
    #if 3 > 3
    #define ev_1000ms 0x8U
    #endif
    #if 3 > 4
    #define ev_1000ms 0x10U
    #endif
    #if 3 > 5
    #define ev_1000ms 0x20U
    #endif
    #if 3 > 6
    #define ev_1000ms 0x40U
    #endif
    #if 3 > 7
    #define Event_8 0x80U
    #endif
    #if 3 > 8
    #define Event_9 0x100U
    #endif
    #if 3 > 9
    #define Event_10 0x200U
    #endif
    #if 3 > 10
    #define Event_11 0x400U
    #endif
    #if 3 > 11
    #define Event_12 0x800U
    #endif
    #if 3 > 12
    #define Event_13 0x1000U
    #endif
    #if 3 > 13
    #define Event_14 0x2000U
    #endif
    #if 3 > 14
    #define Event_15 0x4000U
    #endif
    #if 3 > 15
    #define Event_16 0x8000U
    #endif
    #if 3 > 16
    #define Event_17 0x10000U
    #endif
    #if 3 > 17
    #define Event_18 0x20000U
    #endif
    #if 3 > 18
    #define Event_19 0x40000U
    #endif
    #if 3 > 19
    #define Event_20 0x80000U
    #endif
    #if 3 > 20
    #define Event_21 0x100000U
    #endif
    #if 3 > 21
    #define Event_22 0x200000U
    #endif
    #if 3 > 22
    #define Event_23 0x400000U
    #endif
    #if 3 > 23
    #define Event_24 0x800000U
    #endif
    #if 3 > 24
    #define Event_25 0x1000000U
    #endif
    #if 3 > 25
    #define Event_26 0x2000000U
    #endif
    #if 3 > 26
    #define Event_27 0x4000000U
    #endif
    #if 3 > 27
    #define Event_28 0x8000000U
    #endif
    #if 3 > 28
    #define Event_29 0x10000000U
    #endif
    #if 3 > 29
    #define Event_30 0x20000000U
    #endif
    #if 3 > 30
    #define Event_31 0x40000000U
    #endif

/* [] END OF FILE */
